// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJRwmk01cx8bzbES2y_jPFFuaIOX3prgY',
    appId: '1:499320620786:web:472e580779055f1afff26b',
    messagingSenderId: '499320620786',
    projectId: 'pokemon-291d7',
    authDomain: 'pokemon-291d7.firebaseapp.com',
    storageBucket: 'pokemon-291d7.appspot.com',
    measurementId: 'G-DBBYZ4P2BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgalJg6r0f7fr5abyBMSB8yBKBksjJZQ',
    appId: '1:499320620786:android:7601862a5c7017bbfff26b',
    messagingSenderId: '499320620786',
    projectId: 'pokemon-291d7',
    storageBucket: 'pokemon-291d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyUUauVB0keUIdxx24Qwep4vfrVfSimQs',
    appId: '1:499320620786:ios:30f66d3b21353b82fff26b',
    messagingSenderId: '499320620786',
    projectId: 'pokemon-291d7',
    storageBucket: 'pokemon-291d7.appspot.com',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyUUauVB0keUIdxx24Qwep4vfrVfSimQs',
    appId: '1:499320620786:ios:21f6274c65f044adfff26b',
    messagingSenderId: '499320620786',
    projectId: 'pokemon-291d7',
    storageBucket: 'pokemon-291d7.appspot.com',
    iosBundleId: 'com.example.pokedex.RunnerTests',
  );
}
